server:
  port: 9191

# 数据库配置
spring:
  main:
    allow-bean-definition-overriding: true #当遇到同样名字的时候，是否允许覆盖注册
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: NewPassWord1.
    url: jdbc:mysql://101.132.65.76/children_lost_dev?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8&autoReconnect=true
    type: com.alibaba.druid.pool.DruidDataSource
    # druid配置
    druid:
      #初始化时建立物理连接的个数
      initial-size: 5
      #最小连接池数量
      min-idle: 5
      #最大连接池数量 maxIdle已经不再使用
      max-active: 20
      #获取连接时最大等待时间，单位毫秒
      max-wait: 60000
      #申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效。
      test-while-idle: true
      #既作为检测的间隔时间又作为testWhileIdel执行的依据
      time-between-eviction-runs-millis: 60000
      #销毁线程时检测当前连接的最后活动时间和当前时间差大于该值时，关闭当前连接
      min-evictable-idle-time-millis: 30000
      #用来检测连接是否有效的sql 必须是一个查询语句
      #mysql中为 select 'x'
      #oracle中为 select 1 from dual
      validation-query: select 'x'
      #申请连接时会执行validationQuery检测连接是否有效,开启会降低性能,默认为true
      test-on-borrow: false
      #归还连接时会执行validationQuery检测连接是否有效,开启会降低性能,默认为true
      test-on-return: false
      #当数据库抛出不可恢复的异常时,抛弃该连接
      # exception-sorter: true
      #是否缓存preparedStatement,mysql5.5+建议开启
      #spring.datasource.druid.pool-prepared-statements=true
      #当值大于0时poolPreparedStatements会自动修改为true
      max-pool-prepared-statement-per-connection-size: 20
      #配置扩展插件
      filters: stat,wall
      #通过connectProperties属性来打开mergeSql功能；慢SQL记录
      #spring.datasource.druid.connection-properties=druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
      #合并多个DruidDataSource的监控数据
      use-global-data-source-stat: true
      #设置访问druid监控页的账号和密码,默认没有
      #spring.datasource.druid.stat-view-servlet.login-username=admin
      #spring.datasource.druid.stat-view-servlet.login-password=admin
      stat-view-servlet:
        login-password: admin
        login-username: admin

  # redis
  redis:
    database: 0 #redis数据库索引
    host: 101.132.65.76 #reids服务器地址
    port: 6379 # 本地redis服务端口
    password: NewPassWord1. # 本地redis密码 ： 为空
    jedis:
      pool:
        max-active: 20 #连接池最大连接数
        max-wait: -1 #连接池最大阻塞等待时间（使用负数标识没有限制）
        max-idle: 10 #连接池中最大空闲连接
        min-idle: 0 #连接池中最小空闲连接
    timeout: 1000 # 连接超时(毫秒)

# mybatis-plus配置
mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: deleted # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
  type-aliases-package: com.lry.lostchildinfo/entity #别名
  mapper-locations: classpath:mapper/*.xml    #mybatis文件
  configuration:
    map-underscore-to-camel-case: true #开启驼峰命名
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # sql日志

#JWT
jwt:
  prefix: Bearer  # 请求前缀
  header: Authentication   # 请求头
  secret: whoareyou  # 盐值
  expire: 86400000 # 过期时间(一天)

#  FTP.ADDRESS=file.7b114.xyz
#  FTP.PORT=21
#  FTP.USERNAME=ftpuser
#  FTP.PASSWORD=ftpuser
#  FTP.BasePATH=/usr/local/my_project/first_demo/image/blog_avater
#  # 访问图片的根路径
#  IMAGE.BASE.URL=https://file.7b114.xyz/blog_avater

# ftp文件上传配置
ftp:
  address: file.7b114.xyz # 路径
  port: 21 # 端口
  username: ftpuser # linux的用户名
  password: ftpuser # linux的密码
  basePath: /usr/local/my_project/first_demo/image/blog_avater #上传路径
  imageBaseUrl: https://file.7b114.xyz/blog_avater # 图片访问根路径



